redhen_relation.redhen_relation_type.*:
  type: config_entity
  label: 'Relation type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
